language: r
warnings_are_errors: false
sudo: required
cache: packages

notifications:
  email:
    recipients:
      - nicolas.casajus@gmail.com

r:
  -oldrel

r_packages:
  - devtools

after_success:
  - Rscript -e 'devtools::install()'
  # - Rscript -e 'pkgdown::build_site()'

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_PAT
#   keep-history: true
#   local-dir: docs
#   on:
#     branch: master
